language: php

php:
  - 7.3

before_script:
  - cp .env.travis .env
  - mysql -e 'create database equipac_ci;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - dev
    - iteracao3
    - iteracao4
    - travisMysql

services:
  - mysql 

notifications:
 email: 
  - unkdev@outlook.com

cache:
 directories:
   - node_modules
   - vendor