language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.3.3

before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

branches:
  only:
  - master
  - dev
  - iteracao3

notifications:
 on_success: never
 on_failure: always
 Here I’ve added the PHP versions that are allowed for the projects.
 before_script allows you to run command before the environment actually executes.
 allow_failures contains the conditions that allow your build to fail.
 notifications will notify you in all scenarios of build success or failure.
 If you are using Symfony 3, you can add this script provided by Antonio Jiménez

language: php

services:
 - mysql

notifications:
 email: unkdev@outlook.com

cache:
 directories:
   - node_modules
   - vendor