language: php

php:
  - 7.3

before_script:
  - cp .env.travis .env
  - mysql -e 'create database equipac_ci;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - dev
    - iteracao3
    - iteracao4

services:
  - mysql

before_install:
  - mysql -u root -p password="root" < scriptMYSQL/equipac_ci.sql  

notifications:
 email: 
  - unkdev@outlook.com

cache:
 directories:
   - node_modules
   - vendor