language: php

php:
  - 7.3

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - dev
    - iteracao3
    - iteracao4
    - travisMysql

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testing_db;'  
  - mysql -u root --default-character-set=utf8 testing_db < scriptMYSQL/equipac_teste.sql

notifications:
 email: 
  - unkdev@outlook.com

cache:
 directories:
   - node_modules
   - vendor