language: php

php:
  - 7.3

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - dev
    - iteracao3
    - iteracao4
    - travisMysql

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

dist: trusty

sudo: required  

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pnew_password
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testing_db;'  
  - mysql -u root testing_db < scriptMYSQL/equipac_teste.sql

notifications:
 email: 
  - unkdev@outlook.com

cache:
 directories:
   - node_modules
   - vendor